maze:
  grid_size: 10
  obstacles:
    emoji: "üü©"
    position:
      - [0, 6]
      - [1, 1]
      - [1, 3]
      - [1, 4]
      - [1, 6]
      - [1, 8]
      - [1, 9]
      - [2, 1]
      - [2, 4]
      - [2, 6]
      - [3, 2]
      - [3, 4]
      - [3, 6]
      - [3, 7]
      - [3, 8]
      - [4, 0]
      - [4, 2]
      - [4, 4]
      - [4, 5]
      - [4, 8]
      - [5, 2]
      - [5, 6]
      - [6, 1]  
      - [6, 2]
      - [6, 3]
      - [6, 4]
      - [6, 6]
      - [6, 7]
      - [6, 9]
      - [7, 4]
      - [7, 6]
      - [8, 0]
      - [8, 1]
      - [8, 2]
      - [8, 4]
      - [8, 6]
      - [8, 8]
      - [9, 4]
      - [9, 8]
  enemies:
    skeleton_emoji: "üíÄ"
    dragon_emoji: "üêâ"
    attack_power: 20
    skeletons:
      - skeleton:
          name: "Skeletor"
          health: 100
          position: [2, 7]
          shield_power : 10
      - skeleton:
          name: "Bones"
          health: 100
          position: [6, 5]
          shield_power : 15
      - skeleton:
          name: "Skull"
          health: 100
          position: [9, 3]
          shield_power : 5
    dragons:
      - dragon:
          name: "Draco"
          health: 100
          position: [0, 5]
          fire_power : 10
      - dragon:
          name: "Smaug"
          health: 100
          position: [5, 7]
          fire_power : 15
      - dragon:
          name: "Puff"
          health: 100
          position: [7, 2]
          fire_power : 5
  items:
    gems:
      emoji: "üíé"
      position: 
        - [0, 9]
        - [5, 3]
        - [9, 0]
    keys:
      emoji: "üîë"
      position: 
        - [0, 8]
        - [2, 5]
        - [7, 7]
        - [7, 5]
    padlocks:
      emoji: "üîí"
      position: 
        - [4, 3]
        - [6, 0]
        - [9, 6]
        - [6, 8]
    arrows:
      emoji: "üèπ"
      position: 
        - [2, 9]
        - [3, 1]
        - [5, 4]
        - [8, 7]
    hearts:
      emoji: "üíñ"
      position: 
        - [0, 0]
        - [4, 6]
        - [3, 5]
        - [8, 3]
  player:
    name: "Arthur"
    health: 1000
    attack_power: 50
    position: [9, 9]
    direction: "up"
    emoji_up: "‚è´" # direction: up
    emoji_down: "‚è¨" # direction: down
    emoji_left: "‚è™" # direction: left
    emoji_right: "‚è©" # direction: right
